"""Setup database (create tables)

Revision ID: 5624192f0a99
Revises: 
Create Date: 2016-03-20 13:25:06.859022

"""

# revision identifiers, used by Alembic.
revision = '5624192f0a99'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    from pytz import timezone
    kolkata_time_zone = timezone('Asia/Kolkata')

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('firstName', sa.String(length=255), nullable=True),
    sa.Column('lastName', sa.String(length=255), nullable=True),
    sa.Column('univ_roll', sa.BigInteger(), nullable=True),
    sa.Column('google_sub', sa.BigInteger(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('gcm_reg_id', sa.String(), nullable=True),
    sa.Column('is_alumnus', sa.Boolean(), nullable=True),
    sa.Column('reg_date', sa.DateTime(timezone=kolkata_time_zone), nullable=True),
    sa.Column('admission_year', sa.SmallInteger(), nullable=True),
    sa.Column('current_semester', sa.SmallInteger(), nullable=True),
    sa.Column('passout_year', sa.SmallInteger(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_google_sub'), 'user', ['google_sub'], unique=True)
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('notice')
    op.drop_index(op.f('ix_user_google_sub'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
