"""Change back google_sub to string

Revision ID: ceae3ff130b5
Revises: 5624192f0a99
Create Date: 2016-04-06 20:42:50.791101

"""

# revision identifiers, used by Alembic.
revision = 'ceae3ff130b5'
down_revision = '5624192f0a99'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'google_sub',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'google_sub',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    ### end Alembic commands ###
