"""Add user date modified column

Revision ID: ec861be8ba97
Revises: ceae3ff130b5
Create Date: 2016-04-15 15:43:17.677348

"""

# revision identifiers, used by Alembic.
revision = 'ec861be8ba97'
down_revision = 'ceae3ff130b5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    from pytz import timezone
    kolkata_time_zone = timezone('Asia/Kolkata')

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_modified', sa.DateTime(timezone=kolkata_time_zone), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_modified')
    ### end Alembic commands ###
